export const ActionTypes={
LOGIN_LOADING:"LOGIN_LOADING",
LOGIN_ERROR:"LOGIN_ERROR",
LOGIN_SUCCESS:"LOGIN_SUCCESS",


REGISTER_LOADING:"REGISTER_LOADING",
REGISTER_ERROR:"REGISTER_ERROR",
REGISTER_SUCCESS:"REGISTER_SUCCESS",
}